
#### general settings

name: 01_IRN_DB_x4_scratch_DIV2K
use_tb_logger: true
model: CLRNet # CVPR
distortion: sr
scale: 4
gpu_ids: [1,0,2]


#### datasets
phase: train
#phase: test

datasets:
  train:
    name: COCO
    mode: LQGT
#    dataroot_GT: /qichaoying/Downloads/Invertible-Image-Rescaling-master/icassp_real/images    # Test images
#    dataroot_GT: /groupshare//Places/test                                        # Places
#    dataroot_GT: /groupshare//CelebA/img/imgs                                          # CelebA
#    dataroot_GT: /groupshare//paris_street_view/paris_train                            # ParisStreetView
    dataroot_GT: /groupshare/COCOdataset/train2017                                   # COCO
#    dataroot_GT: /groupshare//Flickr1024/train                                 # Flicker
#    dataroot_GT: /groupshare//DIV2K_train_HR_image                                # DIV2K
#    dataroot_GT: /groupshare//VOC2012/JPEGImages
#    dataroot_GT: /groupshare//UCID_color/images                                                 # UCID
#    dataroot_GT: //groupshare//ILSVRC2012_img_val                                      # ImageNet
    dataroot_LQ: ~ # path to training reference LR images, not necessary, if not provided, LR images will be generated in dataloader

    use_shuffle: true
    n_workers: 4  # per GPU
    ######## CVPR #########
#    batch_size: 2   # 4
#    GT_size: 256
    ######## Imuge #########
    batch_size: 6  # 4
    GT_size: 512
    #########################
    use_flip: true
    use_rot: true
    color: RGB

  val:
    name: val_DIV2K
    mode: LQGT
    dataroot_GT: /groupshare/COCOdataset/val2017
    dataroot_LQ: ~ # path to validation reference LR images, not necessary, if not provided, LR images will be generated in dataloader


#### network structures

network_G:
  which_model_G:
      subnet_type: DBNet
  in_nc: 3
  out_nc: 3
  block_num: [6, 6]
  scale: 4
  init: xavier


#### path

path:
#  pretrain_model: ../experiments/pretrained_RHI3_fine_models/12100        # RHI3
#  pretrain_model: ../experiments/pretrained_crop_fine_models/32100        # Crop
#  pretrain_model: ../experiments/pretrained_models/fine_models/COCO/22100  # Imuge++ 2100
#  pretrain_model: ../experiments/pretrained_models/fine_models/CelebA/2100  # Imuge++ 2100
#  pretrain_model: ../experiments/pretrained_models/230100
#  pretrain_model: ../experiments/pretrained_models/64100
  ######## Imuge #########
  pretrain_model: /qichaoying/Downloads/Invertible-Image-Rescaling-master/experiments/pretrained_models/fine_models/COCO/22100
  #########################
  strict_load: true
  resume_state: ~


#### training settings: learning rate scheme, loss

train:
  using_self_defined_dataset: 0.0
  new_task: 1.0  # 0:imuge 1:outward imuge
  task_name: ImugeV2 # ImugeV2 # CropLocalize # RHI3
  debug_mode: 0
  save_to_latest: 1.0
  load: 0.0
  lr_G: !!float 1e-4    # 2e-5
  lr_D: !!float 1e-4
  beta1: 0.9 #0.9
  beta2: 0.999 #0.999
  niter: 500000
  warmup_iter: -1  # no warm up

  lr_scheme: MultiStepLR
  lr_steps: [5000, 10000, 15000, 20000, 25000, 30000, 35000, 40000, 45000, 50000,60000,70000,80000,90000,100000]
  lr_gamma: 0.5

  pixel_criterion_forw: l2
  pixel_criterion_back: l1

  manual_seed: 10

  val_freq: !!float 5e3

  lambda_fit_forw: 16.
  lambda_rec_back: 1
  lambda_ce_forw: 1
  weight_decay_G: !!float 1e-5
  gradient_clipping: 10

  current_step: 0


#### logger

logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
