
do_evaluate: false

name: /groupshare/IFA_results
model: IFA # CVPR

model_save_period: 5000
restart_step: 1000

train:
  lr_scratch: !!float 1e-4
  lr_finetune: !!float 2e-5
  beta1: 0.9 #0.9
  beta2: 0.999 #0.999


