
do_evaluate: 2000
minimum_PSNR_caused_by_attack: 25
minimun_PSNR_that_activates_local: 45
use_restore: false
max_psnr: 43
psnr_thresh: 28

#### model path dirs
predictor_folder: /groupshare/IFA_results/model/segment_postprocess/

load_predictor_models: ~ #5_1999_qf_predict.pth #4_3999_qf_predict.pth
consider_mask_prediction: false
do_augment: true

load_restormer_models: 15_3999_qf_predict.pth
load_unet_models: 31_7999_qf_predict.pth
load_invisp_models: 10_7999_qf_predict.pth

#### general settings

gpu_ids: [0,1]

restart_step: 1000
model_save_period: 2000

simulated_resize_indices: [0]
simulated_gblur_indices: [1]
simulated_mblur_indices: [2]
simulated_AWGN_indices: [3]
simulated_strong_JPEG_indices: [4]
simulated_weak_JPEG_indices: []

#simulated_hue: [0]
#simulated_contrast: [1,4]
#simulated_saturation: [2,5]
#simulated_brightness: [3,6]
#simulated_gamma: []

weak_JPEG_lower_bound: 20
strong_JPEG_upper_bound: 14
strong_JPEG_lower_bound: 10



datasets:
  train:
    name: Rerun
    mode: LQGT
#    dataroot_GT: /qichaoying/Downloads/Invertible-Image-Rescaling-master/icassp_real/images    # Test images
#    dataroot_GT: /groupshare//Places/data_256                                        # Places
#    dataroot_GT: /groupshare/CelebA/img/img_celeba_200                                          # CelebA
#    dataroot_GT: /groupshare/paris_street_view/paris_train                            # ParisStreetView
    dataroot_GT: /groupshare/COCOdataset/train2017                                   # COCO
#    dataroot_GT: /groupshare//Flickr1024/train                                 # Flicker
#    dataroot_GT: /groupshare//DIV2K_valid                                # DIV2K
#    dataroot_GT: /groupshare//VOC2012/JPEGImages
#    dataroot_GT: /groupshare//UCID_color/images                                                 # UCID
#    dataroot_GT: /groupshare//ILSVRC2012_img_val                                      # ImageNet
    dataroot_LQ: ~

    use_shuffle: true
    n_workers: 4 # per GPU

    batch_size: 4 # 4
    GT_size: 256 # 608

    color: RGB

  val:
    name: val_DIV2K
    mode: LQGT
    dataroot_GT: /groupshare/COCOdataset/val2017
    dataroot_LQ: ~ # path to validation reference LR images, not necessary, if not provided, LR images will be generated in dataloader
    GT_size: 256
    batch_size: 12


train:
  lr_scratch: !!float 1e-4
  lr_finetune: !!float 2e-5
  beta1: 0.9 #0.9
  beta2: 0.999 #0.999