
do_evaluate: false
restoration_model: unet
predict_PSNR_model: resnet # cmt or resnet

#### model path dirs
predictor_folder: /groupshare/IFA_results/model/IFA_baseline/

load_predictor_models: 22_9_qf_predict.pth #0_13999
minimum_PSNR_caused_by_attack: 20

#### model path for MODE 3:detector
which_model_for_detector: Mantra
load_detector_models: None
feature_dim: 64



#### general settings

gpu_ids: [4]

restart_step: 1000
model_save_period: 4000



datasets:
  train:
    name: Rerun
    mode: LQGT
#    dataroot_GT: /qichaoying/Downloads/Invertible-Image-Rescaling-master/icassp_real/images    # Test images
#    dataroot_GT: /groupshare//Places/data_256                                        # Places
#    dataroot_GT: /groupshare/CelebA/img/img_celeba_200                                          # CelebA
#    dataroot_GT: /groupshare/paris_street_view/paris_train                            # ParisStreetView
    dataroot_GT: /groupshare/COCOdataset/train2017                                   # COCO
#    dataroot_GT: /groupshare//Flickr1024/train                                 # Flicker
#    dataroot_GT: /groupshare//DIV2K_valid                                # DIV2K
#    dataroot_GT: /groupshare//VOC2012/JPEGImages
#    dataroot_GT: /groupshare//UCID_color/images                                                 # UCID
#    dataroot_GT: /groupshare//ILSVRC2012_img_val                                      # ImageNet
    dataroot_LQ: ~

    use_shuffle: true
    n_workers: 2 # per GPU

    batch_size: 32 # 4
    GT_size: 256 # 608

    color: RGB

  val:
    name: val_DIV2K
    mode: LQGT
    dataroot_GT: /groupshare/COCOdataset/val2017
    dataroot_LQ: ~ # path to validation reference LR images, not necessary, if not provided, LR images will be generated in dataloader
    GT_size: 256
    batch_size: 1

    color: RGB


train:
  lr_scratch: !!float 1e-4
  lr_finetune: !!float 2e-5
  beta1: 0.9 #0.9
  beta2: 0.999 #0.999
#  weight_decay_G: !!float 1e-5