
#### general settings

name: /groupshare/ISP_results
use_tb_logger: true
model: ISP # CVPR
distortion: sr
scale: 4

step_acumulate: 1
train_isp_networks: false
train_full_pipeline: true
use_gamma_correction: false
conduct_cropping: false
consider_robost: true
include_isp_inference: true
conduct_augmentation: true
train_inpainting_surrogate_model: false
lower_false_positive: false

psnr_thresh: 40
CE_hyper_param: 0.15
ssim_hyper_param: 0.01
perceptual_hyper_param: 0.004
RAW_L1_hyper_param: 4
L1_hyper_param: 1
style_hyper_param: 1
raw_classes: 5
dtcwt_layers: 16
model_save_period: 1000

load_discriminator_models: 11499
load_RAW_models: 11499 # 10999
load_ISP_models: 20999
### directory
task_name_discriminator_model: my_own_elastic # my_own_elastic or ablation_on_RAW
task_name_KD_JPEG_model: my_own_elastic
task_name_customized_model: ISP_alone

#### datasets
phase: train
only_gen_immunized: 0.0
eval_dataset: COCO
eval_kind: inpainting
eval_attack: NOATK
dataset_name: Rerun
#phase: test

datasets:
  train:
    name: Rerun
    mode: LQGT
#    dataroot_GT: /qichaoying/Downloads/Invertible-Image-Rescaling-master/icassp_real/images    # Test images
#    dataroot_GT: /groupshare//Places/data_256                                        # Places
#    dataroot_GT: /groupshare/CelebA/img/img_celeba_200                                          # CelebA
#    dataroot_GT: /groupshare/paris_street_view/paris_train                            # ParisStreetView
    dataroot_GT: /groupshare/ISP_results/xxhu_test/UNet/FORGERY_0                                   # COCO
#    dataroot_GT: /groupshare//Flickr1024/train                                 # Flicker
#    dataroot_GT: /groupshare//DIV2K_valid                                # DIV2K
#    dataroot_GT: /groupshare//VOC2012/JPEGImages
#    dataroot_GT: /groupshare//UCID_color/images                                                 # UCID
#    dataroot_GT: /groupshare//ILSVRC2012_img_val                                      # ImageNet
    dataroot_LQ: /groupshare/ISP_results/xxhu_test/UNet/MASK

    use_shuffle: true
    n_workers: 3 # per GPU
    ######## CVPR #########
#    batch_size: 2   # 4
#    GT_size: 256
    ######## Imuge #########
    batch_size: 2 # 4
    GT_size: 512 # 608
    #########################
    use_flip: true
    use_rot: true
    color: RGB

  val:
    name: val_DIV2K
    mode: LQGT
    dataroot_GT: /groupshare/ISP_results/xxhu_test/UNet/FORGERY_0
    dataroot_LQ: /groupshare/ISP_results/xxhu_test/UNet/MASK # path to validation reference LR images, not necessary, if not provided, LR images will be generated in dataloader

#### training settings: learning rate scheme, loss

train:
  using_self_defined_dataset: 0.0
  new_task: 1.0  # 0:imuge 1:outward imuge
  task_name: ImugeV2 # ImugeV2 # CropLocalize # RHI3
  debug_mode: 0
  save_to_latest: 1.0
  load: 0.0
  lr_scratch: !!float 2e-5   # 2e-5
  lr_finetune: !!float 2e-5
  beta1: 0.9 #0.9
  beta2: 0.999 #0.999
  niter: 500000 # not necessary
  warmup_iter: -1  # no warm up

  lr_scheme: MultiStepLR
  lr_steps: [20000, 40000, 60000, 80000 ,100000,120000,140000,160000,180000,200000]
  lr_gamma: 0.5

  pixel_criterion_forw: l2
  pixel_criterion_back: l1

  manual_seed: 12

  val_freq: !!float 5e3

  lambda_fit_forw: 16.
  lambda_rec_back: 1
  lambda_ce_forw: 1
  weight_decay_G: !!float 1e-5
  gradient_clipping: 10

  current_step: 0


#### network structures

network_G:
  which_model_G:
      subnet_type: DBNet
  in_nc: 3
  out_nc: 3
  block_num: [6, 6]
  scale: 4
  init: xavier

#### path

path:
#  pretrain_model: ../experiments/pretrained_RHI3_fine_models/12100        # RHI3
#  pretrain_model: ../experiments/pretrained_crop_fine_models/32100        # Crop
#  pretrain_model: ../experiments/pretrained_models/fine_models/COCO/22100  # Imuge++ 2100
#  pretrain_model: ../experiments/pretrained_models/fine_models/CelebA/2100  # Imuge++ 2100
#  pretrain_model: ../experiments/pretrained_models/230100
#  pretrain_model: ../experiments/pretrained_models/64100
  ######## Imuge #########
  pretrain_model: /qichaoying/Downloads/Invertible-Image-Rescaling-master/experiments/pretrained_models/fine_models/COCO/22100
  #########################
  strict_load: true
  resume_state: ~



#### logger

logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
