#### model path dirs
#ISP_folder: /groupshare/ISP_results/complete_results/model/my_own_elastic/
#RAW2RAW_folder: /groupshare/ISP_results/complete_results/model/my_own_elastic/
#detector_folder: /groupshare/ISP_results/complete_results/model/my_own_elastic/

#### general settings

using_which_dataset_for_training: Canon_FiveK # RAISE
using_which_dataset_for_test: Canon_FiveK

train_isp_networks: false
train_full_pipeline: true
train_RAW2RAW: true
train_detector: true

name: /groupshare/ISP_results
model: ISP # CVPR
use_gamma_correction: false
conduct_cropping: true
consider_robost: true
include_isp_inference: true
conduct_augmentation: true

model_save_period: 1000
restart_step: 1000

train:
  lr_scratch: !!float 1e-4
  lr_finetune: !!float 2e-5
  beta1: 0.9 #0.9
  beta2: 0.999 #0.999


