#### model path dirs
ISP_folder: /groupshare/ISP_results/complete_results/model/my_own_elastic/
protection_folder: /groupshare/ISP_results/complete_results/model/ablation_OSN_finish/
detector_folder: /groupshare/ISP_results/complete_results/model/OSN/
MVSS_folder: /groupshare/ISP_results/complete_results/model/ablation_OSN_finish/
OSN_folder: /groupshare/ISP_results/complete_results/model/ablation_OSN_finish/

finetune_detector_name: OSN
#### general settings

CE_hyper_param: 0.001

gpu_ids: [0]

load_discriminator_models: 0
load_RAW_models: 3999 # 13999
load_ISP_models: 43999


datasets:
  train:
    name: Rerun
    mode: LQGT
#    dataroot_GT: /qichaoying/Downloads/Invertible-Image-Rescaling-master/icassp_real/images    # Test images
#    dataroot_GT: /groupshare//Places/data_256                                        # Places
#    dataroot_GT: /groupshare/CelebA/img/img_celeba_200                                          # CelebA
#    dataroot_GT: /groupshare/paris_street_view/paris_train                            # ParisStreetView
    dataroot_GT: /groupshare/COCOdataset/train2017                      # COCO
#    dataroot_GT: /groupshare//Flickr1024/train                                 # Flicker
#    dataroot_GT: /groupshare//DIV2K_valid                                # DIV2K
#    dataroot_GT: /groupshare//VOC2012/JPEGImages
#    dataroot_GT: /groupshare//UCID_color/images                                                 # UCID
#    dataroot_GT: /groupshare//ILSVRC2012_img_val                                      # ImageNet
    dataroot_LQ: ~

    use_shuffle: true
    n_workers: 1 # per GPU

    batch_size: 1 # 4
    GT_size: 512 # 608

    color: RGB

  val:
    name: val_DIV2K
    mode: LQGT
    dataroot_GT: /groupshare/COCOdataset/train2017
    dataroot_LQ: ~ # path to validation reference LR images, not necessary, if not provided, LR images will be generated in dataloader
    GT_size: 512 # 608


#### training settings: learning rate scheme, loss
train:
  lr_scratch: !!float 1e-4
  lr_finetune: !!float 2e-5
  beta1: 0.9 #0.9
  beta2: 0.999 #0.999