#### model path dirs
#ISP_folder: /groupshare/ISP_results/complete_results/model/my_own_elastic/
#RAW2RAW_folder: /groupshare/ISP_results/complete_results/model/my_own_elastic/
#detector_folder: /groupshare/ISP_results/complete_results/model/my_own_elastic/

using_RAW_dataset_training: [0.0,2.0,4.0,5.0,6.0,7.0,8.0]
using_RAW_dataset_testing: [0.0,2.0,4.0,5.0,6.0,7.0,8.0]
using_COCO_like_dataset_training: [1.0,3.0]
using_COCO_like_dataset_testing: [1.0,3.0]
#### general settings



using_which_dataset_for_training: Canon_FiveK # RAISE
using_which_dataset_for_test: Canon_FiveK

name: /groupshare/ISP_results
model: ISP # CVPR
use_gamma_correction: false
conduct_cropping: true
consider_robost: true
include_isp_inference: true
conduct_augmentation: true

model_save_period: 1000
restart_step: 1000

train:
  lr_scratch: !!float 1e-4
  lr_finetune: !!float 2e-5
  beta1: 0.9 #0.9
  beta2: 0.999 #0.999


