
### these variables are the most important, make sure dont mess them up
activate_OSN: false

test_baseline: true
test_restormer: 0
#### load pretrained models: number
load_discriminator_models: 1999 # 9
load_RAW_models: 1999 # 9
load_ISP_models: 20999
load_customized_models: 64999
dtcwt_layers: 16
### directory
task_name_discriminator_model: ablation_on_RAW # my_own_elastic or ablation_on_RAW
task_name_KD_JPEG_model: ablation_on_RAW
task_name_customized_model: ISP_alone
#task_name_ISP_model: UNet


#### general settings

#### test settings
inference_benign_attack_begin_idx: 10
inference_load_real_world_tamper: true
inference_do_subsequent_prediction: true
inference_tamper_index: 2
inference_save_image: false
using_which_model_for_test: discriminator_mask # note: restormer cannot be loaded simultaneously with OSN network, because they share the same variable

####################################################################################
datasets:
  train:
    name: Rerun
    mode: LQGT
#    dataroot_GT: /qichaoying/Downloads/Invertible-Image-Rescaling-master/icassp_real/images    # Test images
#    dataroot_GT: /groupshare//Places/data_256                                        # Places
#    dataroot_GT: /groupshare/CelebA/img/img_celeba_200                                          # CelebA
#    dataroot_GT: /groupshare/paris_street_view/paris_train                            # ParisStreetView
    dataroot_GT: /groupshare/ISP_results/xxhu_test/UNet/FORGERY_0                                   # COCO
#    dataroot_GT: /groupshare//Flickr1024/train                                 # Flicker
#    dataroot_GT: /groupshare//DIV2K_valid                                # DIV2K
#    dataroot_GT: /groupshare//VOC2012/JPEGImages
#    dataroot_GT: /groupshare//UCID_color/images                                                 # UCID
#    dataroot_GT: /groupshare//ILSVRC2012_img_val                                      # ImageNet
    dataroot_LQ: /groupshare/ISP_results/xxhu_test/UNet/MASK

    use_shuffle: true
    n_workers: 1 # per GPU

    batch_size: 1 # 4
    GT_size: 512 # 608

    color: RGB

  val:
    name: val_DIV2K
    mode: LQGT
    dataroot_GT: /groupshare/ISP_results/xxhu_test/UNet/FORGERY_0
    dataroot_LQ: /groupshare/ISP_results/xxhu_test/UNet/MASK # path to validation reference LR images, not necessary, if not provided, LR images will be generated in dataloader
    GT_size: 512


train:
  lr_scratch: !!float 1e-4
  lr_finetune: !!float 2e-5
  beta1: 0.9 #0.9
  beta2: 0.999 #0.999