#### model path dirs
ISP_folder: /groupshare/ISP_results/complete_results/model/ISP_RAISE/
protection_folder: /groupshare/ISP_results/complete_results/model/ours_finished/
detector_folder: /groupshare/ISP_results/complete_results/model/ours_finished/
#MVSS_folder: /groupshare/ISP_results/complete_results/model/my_own_elastic/
#OSN_folder: /groupshare/ISP_results/complete_results/model/my_own_elastic/

finetune_detector_name: CAT

## ours:                                CANON: 12999
## mvss: 30999 (KD 12999)  CANON: 12999 (KD finished_MVSS 12999)
## osn: 12999 (KD 12999)
## ISP canon: 16999  CANON: 10999 (KD finished_OSN 19999)

# restormer: 77999
load_discriminator_models: 11999 #11499
load_RAW_models: 11999 #11499 # 10999
load_ISP_models: 43999 #20999 # new: 43999 # canon: 16999
#load_MVSS_models: 11999
#load_OSN_models: 11999
#load_customized_models: 0

simulated_splicing_indices: [3, 6, 8]
simulated_copymove_indices: [0, 2]
simulated_inpainting_indices: [1, 4, 5, 7]
simulated_copysplicing_indices: []

simulated_resize_indices: [0,5]
simulated_gblur_indices: [1]
simulated_mblur_indices: [2,7]
simulated_AWGN_indices: [4]
simulated_strong_JPEG_indices: [3,6]
simulated_weak_JPEG_indices: []


#### general settings

gpu_ids: [2]
conduct_cropping: true
consider_robost: true
include_isp_inference: true
conduct_augmentation: true

restart_step: 1000
model_save_period: 1000

train_isp_networks: false
#train_full_pipeline: true
train_RAW2RAW: true
train_detector: true
using_which_dataset_for_training: Raise #Canon_FiveK

### directory
task_name_discriminator_model: my_own_elastic # my_own_elastic or ablation_on_RAW
task_name_KD_JPEG_model: my_own_elastic
task_name_customized_model: ISP_alone
task_name_ISP_model: my_own_elastic


datasets:
  train:
    name: Rerun
    mode: LQGT
#    dataroot_GT: /qichaoying/Downloads/Invertible-Image-Rescaling-master/icassp_real/images    # Test images
#    dataroot_GT: /groupshare//Places/data_256                                        # Places
#    dataroot_GT: /groupshare/CelebA/img/img_celeba_200                                          # CelebA
#    dataroot_GT: /groupshare/paris_street_view/paris_train                            # ParisStreetView
    dataroot_GT: /groupshare/ISP_results/xxhu_test/UNet/FORGERY_0                                   # COCO
#    dataroot_GT: /groupshare//Flickr1024/train                                 # Flicker
#    dataroot_GT: /groupshare//DIV2K_valid                                # DIV2K
#    dataroot_GT: /groupshare//VOC2012/JPEGImages
#    dataroot_GT: /groupshare//UCID_color/images                                                 # UCID
#    dataroot_GT: /groupshare//ILSVRC2012_img_val                                      # ImageNet
    dataroot_LQ: /groupshare/ISP_results/xxhu_test/UNet/MASK

    use_shuffle: true
    n_workers: 1 # per GPU

    batch_size: 4 # 4
    GT_size: 512 # 608

    color: RGB

  val:
    name: val_DIV2K
    mode: LQGT
    dataroot_GT: /groupshare/ISP_results/xxhu_test/UNet/FORGERY_0
    dataroot_LQ: /groupshare/ISP_results/xxhu_test/UNet/MASK # path to validation reference LR images, not necessary, if not provided, LR images will be generated in dataloader
    GT_size: 512


train:
  lr_scratch: !!float 1e-4
  lr_finetune: !!float 2e-5
  beta1: 0.9 #0.9
  beta2: 0.999 #0.999